### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by plabadens** [boriselec/RimWorld_ArtAi#6]
I came across your repository and I'm really interested in contributing to the project. In particular, I'd like to add support for local generation using the Automatic111 API, as this would allow the generation pipeline to be a lot more flexible.

However, I noticed that there is currently no licensing details for this repo. Could you kindly specify the license you intend to apply or let me know if there are any plans to include a LICENSE file in the repository?

**Comment by boriselec** [comment]
Added LICENSE.

Your contributions are always welcome. 

For the Automatic111 API to be supported, there's a need to rework the current networking setup. Right now, request generation is synchronous, which isn't quite right. It must be modified to be asynchronous for proper functioning.

**Comment by boriselec** [comment]
.
