### ISSUE TITLE
[BUG] Wrong age description & older pic regardless of actual age

### ISSUE THREAD

**Issue by DreamTourist** [boriselec/RimWorld_ArtAi#8]
One pawn got age 18 description, when she was actually 23.
Another pawn got a granny's wrinkled face, when she was only 28.

**Comment by boriselec** [comment]
Age is rounded to nearest "age switch" point.

https://github.com/boriselec/RimWorld_ArtAi/blob/33f1396833d0ee9044e8fb510ba93b89ec287d41/Source/ArtAi14/ArtAi/Avatar/DescriptionAvatar.cs#L27

Maybe it's better to include in text description something like "teenager", "young", or in twenties/in forties etc

**Comment by DreamTourist** [comment]
Sorry about not including these earlier, seem to have totally forgotten I had them backed up.

The one that got granny face, description:
trigger-happy_jogger_woman_lord_light-skinned_with_long_ink-black_hair_in_maroon_clothes_age_25beautiful_photorealistic_portrait_of_a_human
![trigger-happy_jogger_woman_lord_light-skinned_with_long_ink-black_hair_in_maroon_clothes_age_25beautiful_photorealistic_portrait_of_a_human](https://github.com/boriselec/RimWorld_ArtAi/assets/90088372/974ee26b-e212-466f-93d7-685ad5c637c2)

The one that got age 18 instead of actual 23, description:
thin_nimble_wimp_girl_patron_light-skinned_with_long_dark-black_hair_in_teal_clothes_age_18beautiful_photorealistic_portrait_of_a_human
![thin_nimble_wimp_girl_patron_light-skinned_with_long_dark-black_hair_in_teal_clothes_age_18beautiful_photorealistic_portrait_of_a_human](https://github.com/boriselec/RimWorld_ArtAi/assets/90088372/81954727-d7e3-4922-b8e7-b90201966e74)

Another one that's actually 40 but got 25, description:
jealous_tortured_artist_body_modder_woman_excavator_light-skinned_with_shoulder-length_brown_hair_in_gray_clothes_age_25beautiful_photorealistic_portr3020102913
![JEALOU~1](https://github.com/boriselec/RimWorld_ArtAi/assets/90088372/4a1c797c-6109-4f06-b287-169c226743a4)

Seems like there were a few others with the same wrong age bug.
Mostly 22 or 23 that became 18.

**Comment by boriselec** [comment]
https://github.com/boriselec/RimWorld_ArtAi/commit/911f2cf7deda856e4c4939197d0dec061a646752
